In [48]:
import pandas as np
import pandas as pd

In [49]:
df=pd.read_csv('dataset.csv')
df.head()

,7:00,0.0,0.0.1,0.0.2,0.0.3,0.0.4,0.0.5,0.0.6,0.0.7,0.0.8,0.0.9,0.0.10,0.0.11,0.0.12,0.0.13,0.0.14,0.0.15,4.1
0,7:30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.6
1,8:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.7
2,8:30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.2
3,9:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,11.1
4,9:30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.9

In [50]:
df.columns=['Time','Immobilized bus','B_Truck','Vehicle_ex','Acc_victim','R_over','Fire_Veh','OIF','IIDF','Lack_of_el','Fire','Po_flooding','Manifestations','DNT','TR','Sem_off','Int_Semaphore','Slowness_in_traffic']

In [51]:
df

,Time,Immobilized bus,B_Truck,Vehicle_ex,Acc_victim,R_over,Fire_Veh,OIF,IIDF,Lack_of_el,Fire,Po_flooding,Manifestations,DNT,TR,Sem_off,Int_Semaphore,Slowness_in_traffic
0,7:30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.6
1,8:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.7
2,8:30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.2
3,9:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,11.1
4,9:30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129,18:00,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,17.8
130,18:30,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,18.1
131,19:00,1.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,17.7
132,19:30,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,17.4
133,20:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,12.1

In [52]:
df.shape

(134, 18)

In [53]:
df.dtypes

Time                    object
Immobilized bus        float64
B_Truck                float64
Vehicle_ex             float64
Acc_victim             float64
R_over                 float64
Fire_Veh               float64
OIF                    float64
IIDF                   float64
Lack_of_el             float64
Fire                   float64
Po_flooding            float64
Manifestations         float64
DNT                    float64
TR                     float64
Sem_off                float64
Int_Semaphore          float64
Slowness_in_traffic    float64
dtype: object

In [54]:
df.describe()

,Immobilized bus,B_Truck,Vehicle_ex,Acc_victim,R_over,Fire_Veh,OIF,IIDF,Lack_of_el,Fire,Po_flooding,Manifestations,DNT,TR,Sem_off,Int_Semaphore,Slowness_in_traffic
count,134.000000,134.000000,134.000000,134.000000,134.000000,134.000000,134.000000,134.000000,134.000000,134.000000,134.000000,134.000000,134.000000,134.000000,134.000000,134.000000,134.000000
mean,0.343284,0.880597,0.029851,0.425373,0.119403,0.007463,0.007463,0.007463,0.119403,0.007463,0.119403,0.052239,0.231343,0.044776,0.126866,0.014925,10.096269
std,0.661560,1.103956,0.170814,0.697761,0.347813,0.086387,0.086387,0.086387,0.506273,0.086387,0.715508,0.223343,0.821828,0.207588,0.465690,0.121709,4.348873
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.400000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,7.400000
50%,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,9.100000
75%,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,11.875000
max,4.000000,5.000000,1.000000,3.000000,2.000000,1.000000,1.000000,1.000000,4.000000,1.000000,7.000000,1.000000,8.000000,1.000000,4.000000,1.000000,23.400000

In [55]:
df['Time'] = pd.to_datetime(df['Time'])
df

,Time,Immobilized bus,B_Truck,Vehicle_ex,Acc_victim,R_over,Fire_Veh,OIF,IIDF,Lack_of_el,Fire,Po_flooding,Manifestations,DNT,TR,Sem_off,Int_Semaphore,Slowness_in_traffic
0,2021-09-26 07:30:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.6
1,2021-09-26 08:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.7
2,2021-09-26 08:30:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.2
3,2021-09-26 09:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,11.1
4,2021-09-26 09:30:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129,2021-09-26 18:00:00,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,17.8
130,2021-09-26 18:30:00,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,18.1
131,2021-09-26 19:00:00,1.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,17.7
132,2021-09-26 19:30:00,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,17.4
133,2021-09-26 20:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,12.1

In [56]:
df['Hour']=df.Time.dt.hour
df

,Time,Immobilized bus,B_Truck,Vehicle_ex,Acc_victim,R_over,Fire_Veh,OIF,IIDF,Lack_of_el,Fire,Po_flooding,Manifestations,DNT,TR,Sem_off,Int_Semaphore,Slowness_in_traffic,Hour
0,2021-09-26 07:30:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.6,7
1,2021-09-26 08:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.7,8
2,2021-09-26 08:30:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.2,8
3,2021-09-26 09:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,11.1,9
4,2021-09-26 09:30:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.9,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129,2021-09-26 18:00:00,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,17.8,18
130,2021-09-26 18:30:00,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,18.1,18
131,2021-09-26 19:00:00,1.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,17.7,19
132,2021-09-26 19:30:00,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,17.4,19
133,2021-09-26 20:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,12.1,20

In [57]:
def convert(hour):
    if ((hour > 4) & (hour< 12)):
       return('Morning')
    elif ((hour >= 12) & (hour < 16 )):
       return('Noon')
    elif ((hour >= 16) & (hour < 20 )):
       return('Afternoon')
    elif ((hour >= 20) & (hour < 24 )):
       return('Night')
    elif ((hour > 24) & (hour <= 4 )):
       return('Night')

In [58]:
df.Hour=df['Hour'].apply(lambda x: convert(x))

In [59]:
df

,Time,Immobilized bus,B_Truck,Vehicle_ex,Acc_victim,R_over,Fire_Veh,OIF,IIDF,Lack_of_el,Fire,Po_flooding,Manifestations,DNT,TR,Sem_off,Int_Semaphore,Slowness_in_traffic,Hour
0,2021-09-26 07:30:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.6,Morning
1,2021-09-26 08:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.7,Morning
2,2021-09-26 08:30:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.2,Morning
3,2021-09-26 09:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,11.1,Morning
4,2021-09-26 09:30:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.9,Morning
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129,2021-09-26 18:00:00,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,17.8,Afternoon
130,2021-09-26 18:30:00,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,18.1,Afternoon
131,2021-09-26 19:00:00,1.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,17.7,Afternoon
132,2021-09-26 19:30:00,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,17.4,Afternoon
133,2021-09-26 20:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,12.1,Night

In [60]:
df.Hour.unique()

array(['Morning', 'Noon', 'Afternoon', 'Night'], dtype=object)

In [61]:
df_dummies=pd.get_dummies(df.Hour)

In [62]:
df_dummies

     Afternoon  Morning  Night  Noon
0            0        1      0     0
1            0        1      0     0
2            0        1      0     0
3            0        1      0     0
4            0        1      0     0
..         ...      ...    ...   ...
129          1        0      0     0
130          1        0      0     0
131          1        0      0     0
132          1        0      0     0
133          0        0      1     0

[134 rows x 4 columns]

In [63]:
merged=pd.concat([df,df_dummies], axis=1)

In [64]:
merged

,Time,Immobilized bus,B_Truck,Vehicle_ex,Acc_victim,R_over,Fire_Veh,OIF,IIDF,Lack_of_el,...,DNT,TR,Sem_off,Int_Semaphore,Slowness_in_traffic,Hour,Afternoon,Morning,Night,Noon
0,2021-09-26 07:30:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,6.6,Morning,0,1,0,0
1,2021-09-26 08:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,8.7,Morning,0,1,0,0
2,2021-09-26 08:30:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,9.2,Morning,0,1,0,0
3,2021-09-26 09:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,11.1,Morning,0,1,0,0
4,2021-09-26 09:30:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,10.9,Morning,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129,2021-09-26 18:00:00,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,17.8,Afternoon,1,0,0,0
130,2021-09-26 18:30:00,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,18.1,Afternoon,1,0,0,0
131,2021-09-26 19:00:00,1.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,17.7,Afternoon,1,0,0,0
132,2021-09-26 19:30:00,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,17.4,Afternoon,1,0,0,0
133,2021-09-26 20:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,12.1,Night,0,0,1,0

In [65]:
df=merged.drop(['Hour','Afternoon','Time'], axis=1)
df.head()

,Immobilized bus,B_Truck,Vehicle_ex,Acc_victim,R_over,Fire_Veh,OIF,IIDF,Lack_of_el,Fire,Po_flooding,Manifestations,DNT,TR,Sem_off,Int_Semaphore,Slowness_in_traffic,Morning,Night,Noon
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.6,1,0,0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.7,1,0,0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.2,1,0,0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,11.1,1,0,0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.9,1,0,0

In [78]:
X=df.drop('Slowness_in_traffic', axis=1)
y=df[['Slowness_in_traffic']]

In [79]:
cols=X.columns

In [80]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()

In [81]:
X=scaler.fit_transform(X)
X=pd.DataFrame(X, columns=cols)

In [82]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test= train_test_split(X,y, test_size=0.3)

In [83]:
X_train.shape

(93, 19)

In [84]:
Y_train.shape

(93, 1)

In [86]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()

In [87]:
model.fit(X_train,Y_train)

LinearRegression()

In [89]:
y_pred=model.predict(X_test)

# mean squared error and r-2 score

In [101]:
from sklearn.metrics import mean_squared_error, r2_score
mse = mean_squared_error(Y_test,y_pred)
r2 = r2_score(Y_test,y_pred)
print('mean sqaure error:',mse)
print('R-Sqaured error:',r2)

mean sqaure error: 6.124846392303357
R-Sqaured error: 0.5550700123220779

# median absolute error

In [95]:
from sklearn.metrics import median_absolute_error
median_absolute_error(Y_test,y_pred)

1.4712206656878237

# mean absolute error

In [96]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(Y_test,y_pred)

1.9252904091917222

# Mean absolute percentage error

In [99]:
from sklearn.metrics import mean_absolute_percentage_error
mean_absolute_percentage_error(Y_test,y_pred)

0.2237511545490588